version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/my-react-app
permissions:
  - object: /home/ec2-user/my-react-app
    pattern: "**"
    owner: ec2-user
    group: ec2-user
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: ec2-user
  AfterInstall:
    - location: scripts/build_app.sh
      timeout: 600 # React builds can take longer
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: ec2-user
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: ec2-user
  AfterInstall:
    - location: scripts/set_permissions.sh
      timeout: 300
      runas: ec2-user